Feature/add a new version
gopetbot/messenger pull request #6
Opened 2020-08-18 01:09 UTC by idasilva

2020-08-19 02:30 UTC, alexlopes requested changes
@idasilva algumas request chances iniciais : 

- Existem alguns lugares que estão com `github.com/idasilva/messenger`
- Seria bom padronizarmos os logs, talvez onde está `fmt.Println` colocar o `log`

2020-08-19 02:30 UTC, alexlopes commented on go.mod
> +module github.com/idasilva/messenger
Aqui não deveria ser `gopetbot` ao invés de `idasilva` ?

2020-08-19 02:30 UTC, alexlopes commented on server/server.go
> +	"github.com/idasilva/messenger/handlers"
Aqui não deveria ser `gopetbot` ao invés de `idasilva` ?

2020-08-19 02:30 UTC, alexlopes commented on server/server.go
> +	fmt.Println("Create a simple server!!! Port: ", s.svr.Addr)
Aqui seria bom manter o padrão dos demais usando o `log`

2020-08-19 02:36 UTC, idasilva commented on go.mod
> +module github.com/idasilva/messenger
@alexlopes, certo

2020-08-19 02:37 UTC, idasilva commented on server/server.go
> +	"github.com/idasilva/messenger/handlers"
@alexlopes , certo

2020-08-19 02:40 UTC, idasilva commented on server/server.go
> +	fmt.Println("Create a simple server!!! Port: ", s.svr.Addr)
@alexlopes , certo

2020-08-19 02:56 UTC, alexlopes submitted a review, later dismissed
Boa!

2020-08-19 14:04 UTC, julyanaflores submitted a review, later dismissed

2020-08-19 16:30 UTC, mmoraes4 reviewed
Fumega 🥇

2020-08-19 16:30 UTC, moraes1997mateus commented on Dockerfile
> +CMD ["./main"]
faltou a linha no final do arquivo

2020-08-19 16:30 UTC, moraes1997mateus commented on VERSION
> +0.0.0
aqui também falta a linha vazia.

2020-08-19 16:30 UTC, moraes1997mateus commented on main.go
> +		Handler: handlers.PetProject,
Não acho interessante usar espaços para o alinhamento, mas fica a seu critério.

2020-08-19 16:30 UTC, moraes1997mateus commented on server/server.go
> +			ReadHeaderTimeout: 600 * time.Second,
Não acho interessante usar espaços para o alinhamento, mas fica a seu critério.

2020-08-24 01:38 UTC, idasilva commented on VERSION
> +0.0.0
ok

2020-08-24 01:39 UTC, idasilva commented on main.go
> +		Handler: handlers.PetProject,
@moraes1997mateus, conforme conversamos, esse é um padrão.

2020-08-24 01:40 UTC, idasilva commented on Dockerfile
> +CMD ["./main"]
ok

2020-08-24 16:20 UTC, mmoraes4 approved these changes
🎊

2020-08-31 23:55 UTC, alexlopes approved these changes

2020-09-01 00:00 UTC, merged